---
- name: install packages
  action: apt pkg={{item}} state=installed
  with_items:
    - libsecp256k1-0
    - libsecp256k1-dev
    - libboost-dev
    - libboost-all-dev
    - electrum
    - python-crypto
    - python-pycryptopp
    - python-dev
    - python-flufl.password
    - python-mnemonic
    - python-electrum

- shell: gpg --recv-key 91F3B339B9A02A3D
- file: path=/root/.gnupg/gpg.conf state=touch
- lineinfile:
    dest: /root/.gnupg/gpg.conf
    state: present
    regexp: '91F3B339B9A02A3D'
    line: 'trusted-key 91F3B339B9A02A3D'

- git:
    repo: 'https://github.com/zeromq/libzmq.git'
    dest: /tmp/libzmq
    version: 2d83acceffdef71c62c936487db9478b5478a00c
- shell: |
    cd /tmp/libzmq
    ./autogen.sh
    ./configure --prefix=/usr
- make: chdir=/tmp/libzmq target=install
- file: state=absent path=/tmp/lubzmq

- git:
    repo: 'https://github.com/libbitcoin/libbitcoin.git'
    dest: /tmp/libbitcoin
    version: ddf19b34aac222a834177830de485a665b152a6a
- shell: |
    cd /tmp/libbitcoin
    ./autogen.sh
    ./configure --prefix=/usr
- make: chdir=/tmp/libbitcoin target=install
- file: state=absent path=/tmp/libbitcoin

- git:
    repo: 'https://github.com/libbitcoin/libbitcoin-protocol.git'
    dest: /tmp/libbitcoin-protocol
    version: 57ebd9c32233a76f83038b7655b4a4f8e862bac5
- shell: |
    cd /tmp/libbitcoin-protocol
    ./autogen.sh
    ./configure --prefix=/usr
- make: chdir=/tmp/libbitcoin-protocol target=install
- file: state=absent path=/tmp/libbitcoin-protocol

- git:
    repo: 'https://github.com/libbitcoin/libbitcoin-network.git'
    dest: /tmp/libbitcoin-network
    version: 1e79325d063f4efbbdc1551b2a2cffcf0babb501
- shell: |
    cd /tmp/libbitcoin-network
    ./autogen.sh
    ./configure --prefix=/usr
- make: chdir=/tmp/libbitcoin-network target=install
- file: state=absent path=/tmp/libbitcoin-network

- git:
    repo: 'https://github.com/libbitcoin/libbitcoin-client.git'
    dest: /tmp/libbitcoin-client
    version: de8a7b2232d29e28e47454392dfad9bca532735b
- shell: |
    cd /tmp/libbitcoin-client
    ./autogen.sh
    ./configure --prefix=/usr
- make: chdir=/tmp/libbitcoin-client target=install
- file: state=absent path=/tmp/libbitcoin-client

- git:
    repo: 'https://github.com/libbitcoin/libbitcoin-explorer.git'
    dest: /tmp/libbitcoin-explorer
    version: 231323a5886c2ebf9d33011b8b2c3d49a9af6d52
- shell: |
    cd /tmp/libbitcoin-explorer
    ./autogen.sh
    ./configure --prefix=/usr
- make: chdir=/tmp/libbitcoin-explorer target=install
- file: state=absent path=/tmp/libbitcoin-explorer

- git:
    repo: 'https://github.com/prusnak/bip32utils.git'
    dest: /tmp/bip32utils
    version: dd9c541767a2a8ff60c7868c9f4b03277fabb8ba
- shell: |
    cd /tmp/bip32utils
    git verify-commit dd9c541767a2a8ff60c7868c9f4b03277fabb8ba
    python setup.py install
- file: state=absent path=/tmp/bib32utils

- git:
    repo: 'https://github.com/trezor/python-mnemonic.git'
    dest: /tmp/python-mnemonic
    version: bd441b693271a07ee0ce51f89d3141457785b108
- shell: |
    cd /tmp/python-mnemonic
    git verify-commit dd9c541767a2a8ff60c7868c9f4b03277fabb8ba
    python setup.py install
- file: state=absent path=/tmp/python-mnemonic

- git:
    repo: 'https://github.com/richardkiss/pycoin.git'
    dest: /tmp/pycoin
    version: 39a5f47f21f5f31c68c147dc173d9b2751c3213a
- shell: |
    cd /tmp/pycoin
    python setup.py install
- file: state=absent path=/tmp/pycoin

- git:
    repo: 'https://github.com/Legrandin/pycryptodome.git'
    dest: /tmp/pycryptodome
    version: 2e0f288809bd68a46f881865b0a60f9c54c4751f
- shell: |
    cd /tmp/pycryptodome
    python setup.py install
- file: state=absent path=/tmp/pycryptodome
