---
- apt_key:
    id: 6B274EB1BD0CEED5
    url: "http://apt.galliumos.org/galliumos.gpg"
    state: present

- apt_repository:
    repo: deb http://apt.galliumos.org xenon main
    state: present

- apt:
    name: linux-image-4.8.17-galliumos
    state: latest
    default_release: xenon

- apt:
    name: linux-headers-4.8.17-galliumos
    state: latest
    default_release: xenon

- apt:
    name: linux-modules-4.8.17-galliumos
    state: latest
    default_release: xenon
