---
- apt_repository:
    repo: deb http://ftp.debian.org/debian stretch-backports main
    state: present

- apt_repository:
    repo: deb http://ftp.debian.org/debian/ sid main contrib non-free
    state: present

- name: Install APT packages
  action: apt pkg={{item}} state=latest update_cache=yes
  with_items:
    - sudo
    - git
    - build-essential
    - autoconf
    - automake
    - pkg-config
    - python-setuptools
    - libconfig-dev
    - fsprotect
    - aufs-dkms
    - aufs-tools

- name: Install latest linux kernel and headers
  action: apt pkg={{item}} state=latest
  with_items:
    - linux-image-amd64
    - linux-headers-amd64

- name: Create airgap user
  block:
  - user:
      name: airgap
      shell: /bin/bash
      groups: sudo
      createhome: true
      append: yes
  - file:
      path: /home/airgap/
      state: directory
      recurse: yes
      owner: airgap
      group: airgap
      mode: "0755"
  - file:
      path: /home/airgap/.local/bin
      state: directory
      owner: airgap
      group: airgap
      mode: "0755"
  - shell: passwd --delete airgap
  - lineinfile:
      dest: /etc/sudoers
      state: present
      line: '%sudo ALL=(ALL) NOPASSWD: ALL'
  - file:
      path: /home/airgap/.bash_profile
      state: touch
      owner: airgap
      group: airgap
      mode: "0755"
  - blockinfile:
      dest: /home/airgap/.bash_profile
      state: present
      block: |
        clear
        export PATH="/home/airgap/.local/bin:$PATH"
  - file:
      path: /home/airgap/.hushlogin
      state: touch
      owner: airgap
      group: airgap
      mode: "0755"

- name: Automatic Login
  block:
  - file:
      path: /etc/systemd/system/getty@tty1.service.d
      state: directory
      owner: root
      group: root
      mode: "0755"
  - template:
      src: autologin.conf
      dest: /etc/systemd/system/getty@tty1.service.d/autologin.conf
      mode: "0755"
  - systemd: name=getty@tty1 enabled=yes masked=no

- name: Auto Mount SD Cards
  block:
    - template:
        src: udev-sdcard-automount.rules
        dest: /etc/udev/rules.d/70-udev-sdcard-automount.rules
    - file:
        path: /etc/systemd/system/systemd-udevd.service.d/
        state: directory
        owner: root
        group: root
        mode: "0755"
    - name: Allow systemd-udevd to mount to the system filesystem namespace
      template:
        src: shared-mount.conf
        dest: /etc/systemd/system/systemd-udevd.service.d/shared-mount.conf

- name: Enable DHCP if network device present
  block:
    - blockinfile:
        dest: /etc/systemd/network/dhcp.network
        state: present
        create: yes
        block: |
          [Match]
          Name=en*

          [Network]
          DHCP=ipv4

- name: Enable passwordless ssh for dev or airgap-to-airgap uses
  block:
    - lineinfile:
        dest: /etc/ssh/sshd_config
        state: present
        line: 'PermitEmptyPasswords yes'
    - lineinfile:
        dest: /etc/pam.d/sshd
        state: absent
        line: '@include common-auth'
    - blockinfile:
        dest: /etc/pam.d/sshd
        state: present
        block: |
          auth [success=1 default=ignore] pam_unix.so nullok
          auth requisite pam_deny.so
          auth required pam_permit.so

- name: Immutable rootfs with memory overlay
  block:
    - blockinfile:
        dest: /etc/default/grub
        state: present
        block: |
          GRUB_CMDLINE_LINUX="$GRUB_CMDLINE_LINUX fsprotect=1G quiet splash loglevel=0 console=ttyS0,115200 earlyprintk=ttyS0,115200 nofb"
          #GRUB_HIDDEN_TIMEOUT_QUIET=true
          #GRUB_HIDDEN_TIMEOUT=0
          #GRUB_TIMEOUT=0
    - name: update-initramfs
      command: /usr/sbin/update-initramfs -u
    - name: update-grub
      command: /usr/sbin/update-grub
